export const wines = [
	{
		id: 1,
		pic: "./assets/wines/sauvignonfhk2022.png",
		winer: "Vinařství Filiberk ",
		name: "SAUVIGNON FHK ",
		year: 2022,
		type: ["Bílé", "Suché", "Pozdní sběr"],
		region: "Morava",
		alkohol: 13.5,
		cukr: 1.4,
		kyselinky: 0,
		text: "Kobylský Holý kopec a němčičské Filiberky. Každá trať mu dodává něco...kořenitost, ovocitost, kyselinku a mineralitu. FHK 2022 je naše TOPka ze Sauvigňonů....bílá planná broskev, černý rybíz, mineralita na 1,4g cukrech!!! ... no však ochutnejte sami.",
	},

	{
		id: 2,
		pic: "./wines/",
		winer: "Vinařství Novotný",
		name: "Ryzlink rýnský",
		year: 2020,
		type: ["Bílé", "Suché", "Pozdní sběr"],
		region: "Pálava",
		alkohol: 12.0,
		cukr: 7,
		kyselinky: 8.5,
		text: "Minerální ryzlink s vůní limetky, medu a meruněk. Svěží kyselinka a dlouhá slaná dochuť.",
		skladem: true,
		price: 260,
	},

	{
		id: 3,
		pic: "./assets/wines/testwine.png",
		winer: "Vinařství Štěpánek",
		name: "Pálava",
		year: 2022,
		type: ["Bílé", "Polosladké", "Pozdní sběr"],
		region: "Mikulovská",
		alkohol: 12.5,
		cukr: 27,
		kyselinky: 6.2,
		text: "Aromatická Pálava s tóny růží, liči a koření. Vyvážený zbytkový cukr a jemná kyselinka.",
		skladem: true,
		price: 310,
	},

	{
		id: 4,
		pic: "./assets/wines/testwine.png",
		winer: "Vinařství Hrádek",
		name: "Cabernet Sauvignon",
		year: 2019,
		type: ["Červené", "Suché", "Barrique"],
		region: "Znojemsko",
		alkohol: 14.0,
		cukr: 2,
		kyselinky: 6.9,
		text: "Tmavé ovoce, tabák a vanilka. Plné tělo s jemnými tříslovinami díky zrání v dubovém sudu.",
		skladem: false,
		price: 420,
	},

	{
		id: 5,
		pic: "./assets/wines/testwine.png",
		winer: "Vinařství Solaris",
		name: "Solaris",
		year: 2023,
		type: ["Bílé", "Polosladké", "Moravské zemské"],
		region: "Slovácko",
		alkohol: 11.5,
		cukr: 22,
		kyselinky: 6.0,
		text: "Intenzivní exotická vůně ananasu, manga a květů. Harmonická sladkost.",
		skladem: true,
		price: 230,
	},

	{
		id: 6,
		pic: "./assets/wines/testwine.png",
		winer: "Rodinné vinařství Kozel",
		name: "Zweigeltrebe",
		year: 2021,
		type: ["Červené", "Suché", "Pozdní sběr"],
		region: "Velkopavlovická",
		alkohol: 12.5,
		cukr: 4,
		kyselinky: 5.8,
		text: "Lehčí ovocný styl s tóny višní a bylinek. Středně dlouhá dochuť.",
		skladem: true,
		price: 195,
	},

	{
		id: 7,
		pic: "./assets/wines/testwine.png",
		winer: "Vinařství Bílek",
		name: "Chardonnay",
		year: 2020,
		type: ["Bílé", "Suché", "Barrique"],
		region: "Mikulovská",
		alkohol: 13.0,
		cukr: 3,
		kyselinky: 6.5,
		text: "Krémové tóny másla, vanilky a tropického ovoce. Sud dodává jemnou kouřovost.",
		skladem: false,
		price: 350,
	},

	{
		id: 8,
		pic: "./assets/wines/testwine.png",
		winer: "Vinařství Horák",
		name: "Muškát moravský",
		year: 2023,
		type: ["Bílé", "Polosuché", "Moravské zemské"],
		region: "Slovácko",
		alkohol: 11.0,
		cukr: 14,
		kyselinky: 5.5,
		text: "Svěží muškát s květinovou vůní a lehkou kořenitostí. Velmi pitelné víno.",
		skladem: true,
		price: 170,
	},

	{
		id: 9,
		pic: "./assets/wines/testwine.png",
		winer: "Vinařství Rukavička",
		name: "Frankovka",
		year: 2018,
		type: ["Červené", "Suché", "Pozdní sběr"],
		region: "Velké Pavlovice",
		alkohol: 13.0,
		cukr: 1,
		kyselinky: 7.1,
		text: "Vyvážená frankovka s tóny ostružin, koření a jemného dřeva.",
		skladem: true,
		price: 290,
	},

	{
		id: 10,
		pic: "./assets/wines/testwine.png",
		winer: "Vinařství Valtice",
		name: "Rulandské šedé",
		year: 2021,
		type: ["Bílé", "Suché", "Pozdní sběr"],
		region: "Valtice",
		alkohol: 12.5,
		cukr: 6,
		kyselinky: 6.8,
		text: "Plné, kulaté víno s tóny hrušky, medu a jemné minerality.",
		skladem: true,
		price: 240,
	},

	{
		id: 11,
		pic: "./assets/wines/testwine.png",
		winer: "Vinařství Gala",
		name: "Sauvignon Blanc",
		year: 2022,
		type: ["Bílé", "Suché", "Pozdní sběr"],
		region: "Znojemsko",
		alkohol: 12.5,
		cukr: 5,
		kyselinky: 7.9,
		text: "Intenzivní aroma angreštu, broskví a černého bezu. Výrazně svěží.",
		skladem: true,
		price: 310,
	},

	{
		id: 12,
		pic: "./assets/wines/testwine.png",
		winer: "Vinařství Přibyl",
		name: "Tramín červený",
		year: 2020,
		type: ["Bílé", "Polosladké", "Výběr z hroznů"],
		region: "Mikulovská",
		alkohol: 12.0,
		cukr: 25,
		kyselinky: 5.7,
		text: "Kořenité aroma růží, medu a exotického koření. Hebká sladkost.",
		skladem: false,
		price: 350,
	},

	{
		id: 13,
		pic: "./assets/wines/testwine.png",
		winer: "Vinařství Král",
		name: "Modrý Portugal",
		year: 2019,
		type: ["Červené", "Suché", "Moravské zemské"],
		region: "Slovácko",
		alkohol: 12.0,
		cukr: 2,
		kyselinky: 5.9,
		text: "Jemné červené s tóny švestek a bylinek. Lehká, elegantní struktura.",
		skladem: true,
		price: 180,
	},

	{
		id: 14,
		pic: "./assets/wines/testwine.png",
		winer: "Vinařství Sedláček",
		name: "Veltlínské zelené",
		year: 2023,
		type: ["Bílé", "Suché", "Pozdní sběr"],
		region: "Mikulovská",
		alkohol: 12.0,
		cukr: 4,
		kyselinky: 7.4,
		text: "Pepřový veltlín s citrusovou svěžestí a minerální dochutí.",
		skladem: true,
		price: 220,
	},

	{
		id: 15,
		pic: "./assets/wines/testwine.png",
		winer: "Vinařství Vavřinec",
		name: "Svatovavřinecké",
		year: 2021,
		type: ["Červené", "Polosuché", "Pozdní sběr"],
		region: "Velkopavlovická",
		alkohol: 12.5,
		cukr: 12,
		kyselinky: 6.1,
		text: "Ovocné tóny višní a malin, jemná nasládlost, hladké taniny.",
		skladem: true,
		price: 210,
	},

	{
		id: 16,
		pic: "./assets/wines/testwine.png",
		winer: "Vinařství Horský květ",
		name: "Rulandské bílé",
		year: 2022,
		type: ["Bílé", "Polosuché", "Výběr z hroznů"],
		region: "Pálava",
		alkohol: 12.5,
		cukr: 15,
		kyselinky: 6.3,
		text: "Plné bílé víno s krémovou texturou a tóny vanilky, medu a broskví.",
		skladem: true,
		price: 330,
	},
];
